spring:
  application:
    name: chatbrew-backend
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: "gpt-4o-mini"
          temperature: 0.2
          max-tokens: 200